install:
- pip install -r requirements_test.txt
- pip install tox
- TOX_ENV=py$TRAVIS_PYTHON_VERSION
language: python
matrix:
  allow_failures:
  - env: TOX_ENV="py3.5"
python:
- '2.7'
- '3.5'
script:
- tox -e $TOX_ENV
